### ISSUE TITLE
Add "Back to BotBot.me" link at the top

### ISSUE THREAD

**Issue by mtrythall** [BotBotMe/irc-guide#1]
Currently there is no way to get back to BotBot.me from this mini-site. We need a back links of some sort.

**Comment by mightym** [comment]
I added a link to root on the logo some time ago.

**Comment by mtrythall** [comment]
@mightym I think you're mixing projects up. You have no commits on this project so far! If I'm missing something LMK.

**Comment by jonitrythall** [comment]
added
